Repository paperless-ngx/ansible, pull requests merged in 2023-11, with the labels that each got.

#121 docs: typo in word postgres in README.md
  README.md
Labels: bug, documentation

#122 chore: correct pngx regex to crawl readme.md
  maintenance/vars/scenarios.py
  maintenance/vars/var_collector.py
Labels: skip-changelog

#123 feat(Config): add two config vars
  README.md
  defaults/main.yml
  tasks/paperless_ngx/configuration.yml
Labels: enhancement

#129 build: remove ansible core constraint
  .github/workflows/constraints.txt
Labels: build
