Repository paperless-ngx/ansible, pull requests merged in 2023-08, with the labels that each got.

#89 feat: add support for debian 12
  .github/workflows/code_testing.yml
  .github/workflows/constraints.txt
  README.md
  defaults/main.yml
  meta/main.yml
  tasks/base_dependencies/jbig2enc.yml
  tasks/base_dependencies/main.yml
  tasks/base_dependencies/python.yml
  tasks/base_dependencies/repo_packages.yml
  tasks/paperless_ngx/venv.yml
  vars/main.yml
Labels: enhancement

#90 feat: add support for v1.16 and 1.17
  README.md
  defaults/main.yml
  tasks/paperless_ngx/configuration.yml
Labels: enhancement

#91 style(ansible lint): make compliant with newest version
  .github/workflows/constraints.txt
  molecule/check_fails/converge.yml
Labels: style

#93 build: remove requests dependency
  .github/workflows/constraints.txt
Labels: build

#94 chore: bump version to 1.3.0
  current-version.txt
Labels: skip-changelog

#99 fix: https://github.com/ansible/molecule/issues/4017
  .github/workflows/constraints.txt
Labels: bug

#98 fix(deps): add pkg-config
  tasks/base_dependencies/repo_packages.yml
Labels: bug

#100 chore: bump version to 1.3.1
  current-version.txt
Labels: skip-changelog
