Repository paperless-ngx/ansible, pull requests merged in 2025-05, with the labels that each got.

#221 fix: do not run tasks in checkmode that require registerd variable
  tasks/base_dependencies/jbig2enc.yml
  tasks/base_dependencies/python.yml
  tasks/preparation/platform.yml
  tasks/preparation/pngx_release.yml
Labels: bug

#222 fix: template configuration file directly instead of copying template
  tasks/paperless_ngx/configuration.yml
  tasks/paperless_ngx/release_files.yml
  vars/main.yml
Labels: bug

#232 feat: replace gunicorn webserver with granian
  .gitignore
  .yamllint.yml
  README.md
  create_venv.sh
  defaults/main.yml
  tasks/paperless_ngx/release_files.yml
  tasks/paperless_ngx/systemd_services.yml
  vars/main.yml
Labels: enhancement

#233 style: update YAML linting rules to reflect yaml[octal-values]
  .yamllint.yml
  tasks/paperless_ngx/finalize.yml
  tasks/paperless_ngx/release_files.yml
  tasks/paperless_ngx/systemd_services.yml
Labels: style

#234 feat: add new configuration options for v 2.15
  README.md
  defaults/main.yml
  maintenance/vars/scenarios.py
  tasks/paperless_ngx/configuration.yml
Labels: enhancement

#237 chore: update current version to 4.0.0
  current-version.txt
Labels: skip-changelog
