Repository paperless-ngx/ansible, pull requests merged in 2025-09, with the labels that each got.

#247 fix: issues with newer ansible version where explicit boolean casts are necessary
  handlers/main.yml
  tasks/paperless_ngx/finalize.yml
  tasks/paperless_ngx/main.yml
  tasks/paperless_ngx/systemd_services.yml
  tasks/preparation/pngx_release.yml
Labels: bug

#249 feat: add debian13 support and upgrade jbig2enc tp 0.30.0
  .github/workflows/code_testing.yml
  defaults/main.yml
  tasks/base_dependencies/jbig2enc.yml
  tasks/base_dependencies/repo_packages.yml
  tasks/paperless_ngx/configuration.yml
Labels: enhancement, testing

#250 fix: recursive pattern expansion for paperless_ngx_conf_filename_format
  README.md
  molecule/alternative_installation/converge.yml
  tasks/paperless_ngx/configuration.yml
Labels: bug

#252 chore: bump version to 4.1.0
  current-version.txt
Labels: skip-changelog
